[2024-11-13T08:21:13.794+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-13T08:21:13.827+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_green_taxi.transform_data_task manual__2024-11-13T08:20:55.321382+00:00 [queued]>
[2024-11-13T08:21:13.844+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_green_taxi.transform_data_task manual__2024-11-13T08:20:55.321382+00:00 [queued]>
[2024-11-13T08:21:13.846+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-13T08:21:13.871+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data_task> on 2024-11-13 08:20:55.321382+00:00
[2024-11-13T08:21:13.882+0000] {standard_task_runner.py:64} INFO - Started process 2193 to run task
[2024-11-13T08:21:13.888+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nyc_green_taxi', 'transform_data_task', 'manual__2024-11-13T08:20:55.321382+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpi2xtkabp']
[2024-11-13T08:21:13.892+0000] {standard_task_runner.py:91} INFO - Job 119: Subtask transform_data_task
[2024-11-13T08:21:13.975+0000] {task_command.py:426} INFO - Running <TaskInstance: nyc_green_taxi.transform_data_task manual__2024-11-13T08:20:55.321382+00:00 [running]> on host 7a2cfb7b2df5
[2024-11-13T08:21:14.148+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='nyc_green_taxi' AIRFLOW_CTX_TASK_ID='transform_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-13T08:20:55.321382+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-13T08:20:55.321382+00:00'
[2024-11-13T08:21:14.150+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-13T08:21:14.398+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-13T08:21:14.400+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 97, in transform
    df.to_parquet(os.path.join(path_to_transform_dataset, dataset_transform), index=False)
AttributeError: 'NoneType' object has no attribute 'to_parquet'
[2024-11-13T08:21:14.432+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nyc_green_taxi, task_id=transform_data_task, run_id=manual__2024-11-13T08:20:55.321382+00:00, execution_date=20241113T082055, start_date=20241113T082113, end_date=20241113T082114
[2024-11-13T08:21:14.457+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 119 for task transform_data_task ('NoneType' object has no attribute 'to_parquet'; 2193)
[2024-11-13T08:21:14.510+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-13T08:21:14.558+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-13T08:21:14.562+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
