[2024-11-12T19:48:06.474+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T19:48:06.491+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_green_taxi.load_transform_data_to_bq manual__2024-11-12T19:47:45.040719+00:00 [queued]>
[2024-11-12T19:48:06.498+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_green_taxi.load_transform_data_to_bq manual__2024-11-12T19:47:45.040719+00:00 [queued]>
[2024-11-12T19:48:06.499+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-12T19:48:06.510+0000] {taskinstance.py:2330} INFO - Executing <Task(GCSToBigQueryOperator): load_transform_data_to_bq> on 2024-11-12 19:47:45.040719+00:00
[2024-11-12T19:48:06.516+0000] {standard_task_runner.py:64} INFO - Started process 173 to run task
[2024-11-12T19:48:06.518+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nyc_green_taxi', 'load_transform_data_to_bq', 'manual__2024-11-12T19:47:45.040719+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp3_i4ihoi']
[2024-11-12T19:48:06.520+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask load_transform_data_to_bq
[2024-11-12T19:48:06.559+0000] {task_command.py:426} INFO - Running <TaskInstance: nyc_green_taxi.load_transform_data_to_bq manual__2024-11-12T19:47:45.040719+00:00 [running]> on host 7a2cfb7b2df5
[2024-11-12T19:48:06.626+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='nyc_green_taxi' AIRFLOW_CTX_TASK_ID='load_transform_data_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T19:47:45.040719+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T19:47:45.040719+00:00'
[2024-11-12T19:48:06.627+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T19:48:06.637+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-11-12T19:48:06.638+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-11-12T19:48:06.638+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-11-12T19:48:06.639+0000] {gcs_to_bigquery.py:381} INFO - Using existing BigQuery table for storing data...
[2024-11-12T19:48:06.676+0000] {gcs_to_bigquery.py:385} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'northern-shield-437204-m0', 'datasetId': 'nyc_taxi', 'tableId': 'green_tripdata'}, 'sourceFormat': 'PARQUET', 'sourceUris': ['gs://green_taxi_bucket/transform/tf_green_tripdata_2023-01.parquet'], 'writeDisposition': 'WRITE_EMPTY', 'ignoreUnknownValues': False}}
[2024-11-12T19:48:06.677+0000] {bigquery.py:1702} INFO - Inserting job ***_nyc_green_taxi_load_transform_data_to_bq_2024_11_12T19_47_45_040719_00_00_47b4beaf9468bd6b6ce1d4e1c17130c9
[2024-11-12T19:48:07.954+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T19:48:07.955+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 386, in execute
    job: BigQueryJob | UnknownJob = self._submit_job(self.hook, job_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 308, in _submit_job
    return hook.insert_job(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/common/hooks/base_google.py", line 558, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1705, in insert_job
    job_api_repr._begin()
  File "/home/airflow/.local/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py", line 740, in _begin
    api_response = client._call_api(
  File "/home/airflow/.local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 831, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.9/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.9/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.9/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.9/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/airflow/.local/lib/python3.9/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/northern-shield-437204-m0/jobs?prettyPrint=false: Not found: Dataset northern-shield-437204-m0:nyc_taxi
[2024-11-12T19:48:07.965+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nyc_green_taxi, task_id=load_transform_data_to_bq, run_id=manual__2024-11-12T19:47:45.040719+00:00, execution_date=20241112T194745, start_date=20241112T194806, end_date=20241112T194807
[2024-11-12T19:48:07.978+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task load_transform_data_to_bq (404 POST https://bigquery.googleapis.com/bigquery/v2/projects/northern-shield-437204-m0/jobs?prettyPrint=false: Not found: Dataset northern-shield-437204-m0:nyc_taxi; 173)
[2024-11-12T19:48:07.996+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-12T19:48:08.009+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T19:48:08.011+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
